"""
fix_claude_jsonl.py
-------------------
Auto-repairs JSONL files generated by Claude.ai where unescaped double quotes
inside JSON string values break the outer JSON structure.

Usage:
    python3 fix_claude_jsonl.py <input.jsonl> [output.jsonl]

If output path is omitted, creates <input>_fixed.jsonl automatically.
"""

import json
import sys
from pathlib import Path


def find_string_value_after(text, key, start=0):
    for marker in [f'"{key}": "', f'"{key}":"']:
        idx = text.find(marker, start)
        if idx != -1:
            val_start = idx + len(marker)
            j = val_start
            while j < len(text):
                if text[j] == '\\':
                    j += 2
                    continue
                if text[j] == '"':
                    return text[val_start:j], val_start, j
                j += 1
    return None, -1, -1


def extract_inner_json_by_braces(text, start):
    brace_depth = 0
    in_str = False
    esc = False
    j = start
    while j < len(text):
        c = text[j]
        if esc:
            esc = False; j += 1; continue
        if c == '\\':
            esc = True; j += 1; continue
        if c == '"':
            in_str = not in_str
        if not in_str:
            if c == '{': brace_depth += 1
            elif c == '}':
                brace_depth -= 1
                if brace_depth == 0:
                    return text[start:j + 1], j + 1
        j += 1
    raise ValueError("Unbalanced braces")


def fix_line(raw):
    proposal_id, _, _ = find_string_value_after(raw, "proposal_id")
    industry, _, _    = find_string_value_after(raw, "industry")
    category, _, _    = find_string_value_after(raw, "category")

    is_syn_marker = '"is_synthetic": '
    is_syn_idx = raw.find(is_syn_marker)
    is_synthetic = raw[is_syn_idx + len(is_syn_marker):is_syn_idx + len(is_syn_marker) + 4].startswith('true')

    sys_content, _, _ = find_string_value_after(raw, "content", 0)
    first_content_idx = raw.find('"content": "')
    user_content, _, _ = find_string_value_after(raw, "content", first_content_idx + 1)

    asst_role_idx = raw.rfind('"role": "assistant"')
    asst_content_marker_idx = raw.find('"content": "', asst_role_idx)
    asst_start = asst_content_marker_idx + len('"content": "')

    raw_asst, _ = extract_inner_json_by_braces(raw, asst_start)
    asst_dict = json.loads(raw_asst)

    def normalise(s):
        return s.replace('\\\\n', '\n').replace('\\n', '\n') if s else s

    return {
        "proposal_id": proposal_id,
        "industry": industry,
        "category": category,
        "is_synthetic": is_synthetic,
        "messages": [
            {"role": "system",    "content": normalise(sys_content)},
            {"role": "user",      "content": normalise(user_content)},
            {"role": "assistant", "content": json.dumps(asst_dict, ensure_ascii=False)},
        ],
    }


def process_file(input_path, output_path):
    inp = Path(input_path)
    out = Path(output_path)

    with open(inp, "r", encoding="utf-8") as f:
        raw_lines = [l.rstrip("\n") for l in f if l.strip()]

    print(f"Processing {len(raw_lines)} records from {inp.name}...\n")
    fixed_records = []
    errors = []

    for i, raw in enumerate(raw_lines, 1):
        try:
            obj = json.loads(raw)
            json.loads(obj["messages"][2]["content"])
            fixed_records.append(json.dumps(obj, ensure_ascii=False))
            print(f"  Line {i:>2}: OK     — {obj.get('proposal_id')}")
            continue
        except Exception:
            pass

        try:
            obj = fix_line(raw)
            result = json.dumps(obj, ensure_ascii=False)
            json.loads(result)
            fixed_records.append(result)
            print(f"  Line {i:>2}: FIXED  — {obj.get('proposal_id')}")
        except Exception as e:
            errors.append((i, str(e)))
            print(f"  Line {i:>2}: FAILED — {e}")

    print(f"\n{'='*50}")
    print(f"  Fixed : {len(fixed_records)}/{len(raw_lines)}")
    print(f"  Errors: {len(errors)}/{len(raw_lines)}")

    if fixed_records:
        with open(out, "w", encoding="utf-8") as f:
            for record in fixed_records:
                f.write(record + "\n")
        print(f"\n  Output -> {out}")

    return len(errors) == 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 fix_claude_jsonl.py <input.jsonl> [output.jsonl]")
        sys.exit(1)

    inp = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else inp.replace(".jsonl", "_fixed.jsonl")
    sys.exit(0 if process_file(inp, out) else 1)
